<?php if (($_products = $this->getSaleProducts()) && (count($_products) > 0)): ?>
    <?php $panelHelper = $this->helper('mpanel');
    $size = $panelHelper->convertRatioToMinSize();
    ?>
	<?php $ratio = $size['width']/$size['height']; ?>
	<?php if((Mage::app()->getRequest()->getControllerName() == 'index' && Mage::app()->getRequest()->getActionName() == 'index' && Mage::app()->getRequest()->getModuleName() == 'cms')): ?>
		<?php $width_img = 100; ?>
		<?php $height_img = round($width_img/$ratio); ?>
	<?php else: ?>
		<?php $width_img = 80; ?>
		<?php $height_img = round($width_img/$ratio); ?>
	<?php endif ?>
    <div class="block product-list-block hot-list box-collateral">
   <?php if ($this->getTitle() != ''): ?>
            <div class="title-block">
                <h4 class="title"><span><?php echo $this->getTitle() ?></span></h4>
            </div>
        <?php endif ?>
        <div class="block-content" id="sale_list_slider">
            <?php $i = 0; foreach ($_products as $_product): $i++; ?>
			<?php $cats = $_product->getCategoryIds(); ?>
			<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
                <div class="product-content" style="min-height: <?php echo $height_img ?>px;">
                    <div class="product-top">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
                            <img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width_img, $height_img) ?>" class="img-responsive" />
                        </a>
                    </div>
                    <div class="product-details">
						<div class="top-desc">
							<?php if(count($cats) > 0): ?>
								<?php $j=0; foreach ($cats as $category_id): $j++; ?>
									<?php if($j ==2 ){ break; } ?>
									<?php $_cat = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($category_id); ?>
									<div class="text-desc cate-name no-cp">
										<div class="text">
											<span><?php echo $_cat->getName(); ?></span>
										</div>
									</div>
								<?php endforeach; ?>
							<?php else: ?>
								<div class="text-desc cate-name no-cp">
									<div class="text">
										<span><?php echo $this->__('Sale Products') ?></span>
									</div>
								</div>
							<?php endif ?>
							<?php if ($this->helper('wishlist')->isAllow() && $panelHelper->isShowWishList()): ?>
							<div class="controls">
								<ul class="icon-links">
									<li class="wl-item"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" <?php if (!$panelHelper->checkInWishilist($_product)) : ?>class="no-active"<?php endif ?>><em class="fa <?php if ($panelHelper->checkInWishilist($_product)) : ?>fa-heart<?php else: ?>fa-heart-o<?php endif ?>"></em></button></li>
								</ul>
							</div>
							<?php endif; ?>
						</div>
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a></p>
                        <?php echo $this->getPriceHtml($_product, true) ?>
						<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short','');?>
                    </div>
                </div>
			<?php endforeach ?>
        </div>
    </div>
    <?php else: ?>
    <div class="block product-list-block featured-list box-collateral">
    <?php if ($this->getTitle() != ''): ?>
		<div class="title-block">
			<h4 class="title"><span><?php echo $this->getTitle() ?></span></h4>
		</div>
    <?php endif ?>
        <div class="block-content">
            <div class="alert alert-danger">
                <p><?php echo $this->__('There are no products matching the selection.') ?></p>
            </div>
        </div>
    </div>
<?php endif; ?>