<?php if (($_products = $this->getSpecialProducts('featured')) && (count($_products)>0)): ?>
	<?php $helper = $this->helper('mpanel') ?>
	<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
	<?php if(isset($_GET['perrow'])){
		$col = $_GET['perrow'];
	}else{
		if($this->getCountPerRow()){
			$col = $this->getCountPerRow();
		}
		else{
			$col = 3;
		}
	}
		
		$col = $helper->convertColRowCustom($col);
	?>
<?php if($this->getRequest()->getParam('perrow')): ?>
	<?php $perrow = $this->getRequest()->getParam('perrow') ?>
<?php else: ?>
	<?php $perrow = $this->getCountPerRow() ?>
<?php endif ?>
	<?php $i=0; foreach ($_products->getItems() as $_product): $i++; ?>
		<?php $cats = $_product->getCategoryIds(); ?>
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
		<?php $class = $helper->getItemClass($perrow, $i) ?>
		<li class="item <?php if($col !=''): ?>col-md-<?php echo $col; ?> col-sm-6 col-xs-6<?php endif; ?><?php echo $class ?>">
			<div class="product-content">
				<div class="product-top">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
						<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
							alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
						<?php endif ?>
					</a>
					<?php echo $helper->getProductLabel($_product) ?>
					<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
						<div class="action-quickview">
							<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view btn-full" 
							onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em><?php echo $this->__('Quick view'); ?></button>
						</div>
					<?php endif ?>
				</div>
				<div class="product-desc">
					<div class="top-desc">
						<?php if(count($cats) > 0): ?>
							<?php $j=0; foreach ($cats as $category_id): $j++; ?>
								<?php if($j ==2 ){ break; } ?>
								<?php $_cat = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($category_id); ?>
								<div class="text-desc cate-name">
									<div class="text">
										<span><?php echo $_cat->getName(); ?></span>
									</div>
								</div>
							<?php endforeach; ?>
						<?php else: ?>
							<div class="text-desc cate-name">
								<div class="text">
									<span><?php echo $this->__('Featured Products') ?></span>
								</div>
							</div>
						<?php endif ?>
						<div class="controls">
							<ul class="icon-links">
								<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
									<li class="wl-item"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" <?php if (!$helper->checkInWishilist($_product)) : ?>class="no-active"<?php endif ?>><em class="fa <?php if ($helper->checkInWishilist($_product)) : ?>fa-heart<?php else: ?>fa-heart-o<?php endif ?>"></em></button></li>
								<?php endif; ?>
								<?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && $helper->isShowCompare()): ?>
									<li><button class="btn-compare" type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-sliders"></em></button></li>
								<?php endif; ?>
							</ul>
						</div>
					</div>
					<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
					<div class="bottom-desc">
					<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
					<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short','');?>
					<?php if($helper->isShowAddtoCart()): ?>
						<?php if ($_product->isSaleable()): ?>
							<div class="add-cart-item">
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><em class="fa fa-shopping-cart"></em><?php echo $this->__('Add to Cart'); ?></button>
							</div>
						<?php else: ?>
							<div class="add-cart-item">
								<span class="text-soul"><?php echo $this->__('Out of Stock'); ?></span>
							</div>
						<?php endif; ?>
					<?php endif; ?>
					</div>
				</div>
			</div>
		</li>
	<?php endforeach ?>
<?php else: ?>		
    <div class="alert alert-danger no-product-display">
        <p><?php echo $this->__('There are no products matching the selection.') ?></p>
    </div>
<?php endif ?>