<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');
	$helper = $this->helper('mpanel');
	$widgetId = $this->getWidgetId();
?>
<?php $_columnCount = $this->getColumn(); ?>
<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
<?php if(count($_productCollection)>0): ?>
	<div class="deal-container block-to-deals">
		<?php if(count($_productCollection) == 1): ?>
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper">
					<div class="title-inline">
						<h3 class="heading full text-uppercase"><span><?php echo $this->getTitle() ?></span></h3>
					</div>
				</div>
			<?php else: ?>
				<div class="title-inline">
					<h3 class="heading full text-uppercase"><span><?php echo $this->__('Hot deal everyday') ?></span></h3>
				</div>
			<?php endif ?>
			<div class="molly_sub_title_deals"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('molly_sub_title_deals')->setCanEdit(1)->toHtml(); ?></div>
			<?php foreach ($_productCollection as $product): ?>
				<?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
					<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/price.phtml')->setProductId($_product->getId())->setData("widgetId",$widgetId)->toHtml(); ?>
					<div><button type="button" onclick="setLocation('<?php echo Mage::getBaseUrl().'deals'; ?>')" class="btn btn-primary btn-lg"><?php echo $this->__('Shop now') ?></button></div>
			<?php endforeach ?>
		<?php endif ?>
	</div>
<?php endif ?>
<?php endif ?>