<?php $helper = $this->helper('mpanel') ?>
<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
	<?php $widgetId = $this->getWidgetId();?>
	<?php $productCollection = $this->getProductCollection(); ?>
	<?php if(count($productCollection)>0): ?>
	<div class="slider-deal">
		<?php if($this->getTitle()!=''): ?>
			<div class="carousel_wrapper">
				<div class="title-block">
					<h4 class="title"><span><?php echo $this->getTitle() ?></span></h4>
				</div>
			</div>
		<?php endif ?>
		<div id="deal_products" class="owl-carousel deal-carousel .products-grid">
			<?php $i= 0; foreach($productCollection as $product): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
			<?php $cats = $_product->getCategoryIds(); ?>
				<div class="item">
					<div class="product-content">
						<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
								<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							</a>
							<div class="discount-save">
								<div class="save-content">
									<div class="percent">
										<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
										<?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
										<?php echo $percent ?>%
									</div>
								</div>
							</div>
						</div>
						<div class="product-desc">
							<div class="top-desc">
								<?php if(count($cats) > 0): ?>
									<?php $j=0; foreach ($cats as $category_id): $j++; ?>
										<?php if($j ==2 ){ break; } ?>
										<?php $_cat = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($category_id); ?>
										<div class="text-desc cate-name no-cp">
											<div class="text">
												<span><?php echo $_cat->getName(); ?></span>
											</div>
										</div>
									<?php endforeach; ?>
								<?php else: ?>
									<div class="text-desc cate-name no-cp">
										<div class="text">
											<span><?php echo $this->__('Featured Products') ?></span>
										</div>
									</div>
								<?php endif ?>
								<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
									<div class="controls">
										<ul class="icon-links">
											<li class="wl-item"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" <?php if (!$helper->checkInWishilist($_product)) : ?>class="no-active"<?php endif ?>><em class="fa <?php if ($helper->checkInWishilist($_product)) : ?>fa-heart<?php else: ?>fa-heart-o<?php endif ?>"></em></button></li>
										</ul>
									</div>
								<?php endif ?>
							</div>
							<p class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a>
							</p>
							<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
							<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short','');?>
							<div class="add-info">
								<div class="addcart-button">
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-primary btn-lg" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>')"><?php echo $this->__('Buy Now'); ?></button>
								</div>
								<div class="item-info">
									<!--div class="sold">
										<?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
									</div-->
									<div class="item-left">
										<?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
										<?php if($itemLeft!=''): ?>
											<?php if($itemLeft>1): ?>
												<?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
											<?php else: ?>
												<?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
											<?php endif ?>
										<?php else: ?>
											<?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
										<?php endif ?>
									</div>
								</div>
							</div>
						</div>
						<div class="slide-deals">
							<div class="deals-info">
								<div class="time-left">
									<div class="note"><?php echo $this->__('Time left') ?></div>
									<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->setData("widgetId", $widgetId)->toHtml(); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>	
		<script type="text/javascript">
			dinitSlider('deal_products', <?php echo $this->getColumn() ?>, <?php echo $this->getAutoPlay()?>, <?php echo $this->getStopHover()?>, <?php echo $this->getNavigation()?>, <?php echo $this->getPagination()?>);
		</script>
	<?php endif ?>
<?php endif ?>
