<?php $portfolios = $this->getPortfolios() ?>
<div class="portfolio-container portfolio-grid">
	<?php if($this->getTitle()): ?>
		<div class="title-inline" style="margin-bottom: 30px;">
			<h3 class="heading full text-uppercase"><span><?php echo $this->getTitle() ?></span></h3>
		</div>
	<?php endif ?>
	<?php if(count($portfolios)>0): ?>
		<?php 
			$helper = $this->helper('mpanel');
			$col = $this->getColumn();
			$col = $helper->convertColRowCustom($col);
		?>
		<div class="row">
		<?php if($this->getSlider()==1): ?>
			<div class="owl-carousel portfolio-carousel" id="portfolio_carousel">
		<?php else: ?>
			<div class="<?php if($col == 'custom-5' || $col == 'custom-7' || $col == 'custom-8'): ?> products-grid-<?php echo $col; ?><?php endif; ?>">
		<?php endif ?>
			<?php foreach($portfolios as $portfolio): ?>
				<?php if($this->getSlider()==1): ?>
					<div class="item">
				<?php else: ?>
					<div class="<?php if($col !=''): ?>col-md-<?php echo $col; ?> col-sm-6 col-xs-12<?php endif; ?>">
				<?php endif ?>
				<div class="porfolio-content">
					<div class="portfolio-top-content">
						<a class="porfolio-image" href="<?php echo $this->getUrl('portfolio/view/index', array('id'=>$portfolio->getId())) ?>"><img src="<?php echo $this->helper('portfolio')->getThumbnail($portfolio)?>" alt="" class="img-responsive"/></a>
						<a class="view" href="<?php echo $this->getUrl('portfolio/view/index', array('id'=>$portfolio->getId())) ?>"><span class="hover-info">
							<span class="fa fa-search"></span>
						</span></a>
					</div>
					<div class="portfolio-bottom-content">
						<h5 class="portfolio-name text-uppercase"><a href="<?php echo $this->getUrl('portfolio/view/index', array('id'=>$portfolio->getId())) ?>"><?php echo $portfolio->getName() ?></a></h5>
						<p class="category-link text-desc"><?php echo $this->helper('portfolio')->getCategoriesLink($portfolio)?></p>
					</div>
				</div>
				</div>
			<?php endforeach ?>
			
		</div>
		</div>
		<?php if($this->getSlider()==1): ?>
			<script type="text/javascript">
				initSlider('portfolio_carousel', <?php echo $this->getColumn() ?>, <?php echo $this->getAutoPlay()?>, <?php echo $this->getStopHover()?>, <?php echo $this->getNavigation()?>, <?php echo $this->getPagination()?>);
			</script>
		<?php endif ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There are no portfolios matching the selection.') ?></p>
	<?php endif ?>
</div>