<?php if ($posts = $this->getRecent()): ?>
	<div class="block block-recent-blog">
		<div class="title-block">
			<h4 class="title"><span><?php echo Mage::helper('blog')->__('Recent Posts'); ?></span></h4>
		</div>
		<div class="block-content">
			<div class="menu-recent">
				<ul>
					<?php $i = 0; ?>
					<?php $countPost = count($posts); ?>
					<?php foreach ($posts as $post): ?>
					<?php $i++; ?>
					<?php if($i==5){ break;} ?>
						<li <?php if($i == $countPost || $i == 4): ?>class="last"<?php endif ?>>
							<?php if ($post->getFeaturedImage() != ''): ?>
								<a class="blog_link_img" href="<?php echo $post->getAddress(); ?>" >
									<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/' . $post->getFeaturedImage(); ?>"/>
								</a>
							<?php endif ?>
							<div class="blog-desc">
								<h6 class="text-uppercase"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h6>
							</div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
<?php endif; ?>
<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
	<div class="block block-blog">
		<div class="title-block">
			<h4 class="title"><span><?php echo Mage::helper('blog')->__('Categories'); ?></span></h4>
		</div>
		<div class="block-content vertical-menu">
			<div class="menu-categories">
				<ul>
					<?php $cats = $this->getCategories(); ?>
					<?php $countCats = count($cats); ?>
					<?php $i = 0; foreach ($cats as $cat): $i++; ?>
						<li <?php if($i == 1): ?>class="first"<?php endif ?>><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
<?php endif; ?>
<?php echo $this->getChildHtml('blog_tags'); ?>