<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="row">
	<div class="col-xs-12">
		<div class="post-detail">
			<h2 class="title-blog"><?php echo $post->getTitle(); ?></h2>
			<div class="latest-post-decs text-desc">
				<span class="user-author"><?php echo $post->getUser(); ?></span>
				<span class="create-time"><?php echo $post->getCreatedTime(); ?></span>
				<?php $comments = $this->getCommentCount(); ?>
				<?php $num = count($comments) ?>
				<?php 	if($num > 1){ 
							$many_string = "s";
						}elseif($num == 1){ 
							$many_string = "";
						}else {
							$many_string = "";
							$num = 0;
						} ?>
				<?php $fomart_string =  "%s Comment%s";?>
				<?php if ($this->getCommentsEnabled()): ?>
					<?php ($post->getCommentCount() >= 1) ? $post->getCommentCount() : 0 ?> <span class="comments"><a class="comments" href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?>&nbsp;<?php echo sprintf($fomart_string, $num, $many_string); ?></a></span>
				<?php endif; ?>
			</div>
			<?php if ($post->getImage() != ''): ?>
				<div class="post-img">
					<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/images/' . $post->getImage(); ?>"/>
				</div>
			<?php endif ?>
			<?php if(count(Mage::getBlockSingleton('blog/blog')->getTagsHtml($post))> 0): ?><div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div><?php endif ?>
			<?php echo $this->getBookmarkHtml($post) ?>
			<div class="postContent"><?php echo $post->getPostContent(); ?></div>
			
			<!-- Share -->
			<?php if(Mage::getStoreConfig('mpanel/share_this/blog_detail')): ?>
				<div class="social-icons social-share-mg">
					<p><?php echo Mage::helper('blog')->__('SHARE THIS:'); ?></p>
					<?php echo Mage::getStoreConfig('mpanel/share_this/span_tags') ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
</div>
<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
<div class="comment-blog">
    <?php $comments = $this->getComment(); ?>
	<?php echo Mage::getStoreConfig('blog_comments_page_count') ?>
	<?php $len = count($comments) ?>
	<?php if($len > 0): ?>
	<div class="comment-box">
		<div class="title-inline"><a name="commentBox" ></a>
			<h3 class="text-uppercase heading full"><span><?php echo $this->__(' Comments') ?></span></h3>
		</div>
		<?php $i=0; foreach ($comments as $comment) : $i++; ?>
			<div class="row">
				<div class="col-xs-12">
					<div class="commentWrapper <?php if($i == $number): ?>last<?php endif ?>">
						<div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
						<div class="commentDetails">
							<div class="pull-left text-uppercase"><?php echo $comment->getUser(); ?></div>
							<div class="pull-right text-desc"><?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
						</div>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
		<div class="toolbar-bottom">
			<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
		</div>
	</div>
	<?php endif ?>

    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">
                    <fieldset class="group-select">
						<div class="title-inline">
							<h3 class="text-uppercase heading full"><span><?php echo Mage::helper('blog')->__('Leave a Comment') ?></span></h3>
						</div>
                        <ul class="form-list">
							<li class="icon-form"><i class="pe-7s-user"></i></li>
                            <li>
                                <div class="form-group input-box aw-blog-comment-area">
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;" cols="50" rows="5"   placeholder="<?php echo $this->__('Your Comment*') ?>"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <button class="form-button btn btn-default btn-lg" type="submit"><span><span><?php echo Mage::helper('blog')->__('Add Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>

            <?php else: ?>
				<div class="title-inline">
					<h3 class="text-uppercase heading full"><span><?php echo Mage::helper('blog')->__('Leave a Comment') ?></span></h3>
				</div>
				<div class="alert alert-warning text-center">
					<p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
					<p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
				</div>
			<?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <fieldset class="group-select">
					<div class="title-inline">
						<h3 class="text-uppercase heading full"><span><?php echo Mage::helper('blog')->__('Leave a Comment') ?></span></h3>
					</div>
                    <ul class="form-list">
                        <li>
							<div class="row">
								<div class="form-group col-xs-12">	
									<div class="row">
										<div class="col-sm-6 col-xs-12 input-box">
											<input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" placeholder="<?php echo $this->__('Your Name*') ?>" />
										</div>
										<div class="col-sm-6 col-xs-12 input-box">
											<input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text"  placeholder="<?php echo $this->__('Your Email*') ?>"/>
										</div>
									</div>
								</div>
								<div class="form-group col-xs-12 input-box aw-blog-comment-area">
									<textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;" cols="50" rows="5"  placeholder="<?php echo $this->__('Your Comment*') ?>"><?php echo $this->getCommentText(); ?></textarea>
								</div>
							</div>
                        </li>

                        <?php if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) { ?>
						<li>
							<?php require_once 'recaptcha/recaptchalib-aw.php';

							// Get a key from http://recaptcha.net/api/getkey
							$publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
							$privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
							$error = null;

							echo recaptcha_get_html($publickey, $error); ?>
						</li>
						<?php } ?>
                    </ul>
                </fieldset>
                <div class="button-set">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <button class="btn btn-sm btn-default btn-lg form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Add Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
</div>
<?php endif; ?>