<?php if (Mage::getStoreConfig(AW_Blog_Helper_Config::XML_TAGCLOUD_SIZE) && $this->getCollection()->count()): ?>
    <div class="block block-post-tag">
		<div class="title-block">
			<h4 class="title"><span><?php echo Mage::helper('blog')->__('Tags'); ?></span></h4>
		</div>
		<div class="block-content">
			<ul class="tagcloud">
				<?php foreach ($this->getCollection() as $tag): ?>
					<li><a class="a-tags tag-count-<?php echo $this->getTagWeight($tag) ?>" href="<?php echo $this->getTagHref($tag) ?>"><?php echo $tag->getTag() ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>