<?php $posts = $this->getRecent() ?>
<?php if (count($posts)>0): ?>
	<div class="widget-latest-post">
		<?php if($this->getTitle() && $this->getTitle()!=''): ?>
			<div class="title-content">
				<h2><?php echo $this->getTitle(); ?></h2>
			</div>
		<?php endif ?>
		<?php if($this->getViewMode()=='grid'): ?>
			<?php if($this->getSlider()==1): ?>
				<div class="row">
					<div class="owl-carousel latest-post-carousel" id="latest-post-carousel" data-plugin-options='{"items": 1, "autoHeight": true}'>
						<?php $i=0; foreach ($posts as $post): ?>
							<div class="item blog-view-container">
								<div class="latest-post-img">
									<?php if ($post->getFeaturedImage() != ''): ?>
										<a class="blog_link_img" href="<?php echo $post->getAddress(); ?>" >
											<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/' . $post->getFeaturedImage(); ?>"/>
										</a>
									<?php endif ?>
									<a href="<?php echo $post->getAddress(); ?>" class="read-more"><span class="fa fa-search">&nbsp;</span><?php echo Mage::helper('blog')->__('Read more'); ?></a>
									<div class="day-desc">
										<span class="day"><?php echo date('d', strtotime($post->getCreatedTime())) ?></span>
										<span class="month"><?php echo date('M', strtotime($post->getCreatedTime())) ?></span>
									</div>
								</div>
								<div class="latest-post-decs">
									<div class="latest-name">
										<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
									</div>
									<div class="latest-date">
										<div class="post-info text-desc">
											<span class="user-author"><?php echo $post->getUser(); ?></span>
											<?php if ($this->getCommentsEnabled()): ?>
												<?php $num = $post->getCommentCount(); ?>
												<?php 	if($num > 1){ 
															$many_string = "s";
														}elseif($num == 1){ 
															$many_string = "";
														}else {
															$many_string = "";
															$num = 0;
														} ?>
												<?php $fomart_string =  "%s Comment%s";?>
												<span><a class="comments" href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo sprintf($fomart_string, $num, $many_string); ?></a></span>
											<?php endif; ?>
										</div>
										
									</div>
									<?php if($post->getShortContent()): ?>
										<p class="short-content">
											<?php if($this->getCharacterCount()!=''): ?>
												<?php echo Mage::helper('core/string')->truncate(strip_tags($post->getShortContent()), $this->getCharacterCount()); ?>
											<?php else: ?>
												<?php echo strip_tags($post->getShortContent()); ?>
											<?php endif ?>
										</p>
									<?php endif ?>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				</div>
				<script type="text/javascript">
					initSlider('latest-post-carousel', <?php echo $this->getColumn() ?>, <?php echo $this->getAutoPlay()?>, <?php echo $this->getStopHover()?>, <?php echo $this->getNavigation()?>, <?php echo $this->getPagination()?>);
				</script>
			<?php else: ?>
				<?php $panelHelper = $this->helper('mpanel'); ?>
				<?php $col =  $this->getColumn(); ?>
				<?php $col = $panelHelper->convertColRowCustom($col); ?>
				<div class="latest-post-container row">
					<?php $i=0; foreach ($posts as $post): ?>
							<div class="item col-md-<?php echo $col ?> col-sm-6 col-xs-12 blog-view-container">
								<div class="latest-post-img">
									<?php if ($post->getFeaturedImage() != ''): ?>
										<a class="blog_link_img" href="<?php echo $post->getAddress(); ?>" >
											<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/' . $post->getFeaturedImage(); ?>"/>
										</a>
									<?php endif ?>
									<a href="<?php echo $post->getAddress(); ?>" class="read-more"><span class="fa fa-search">&nbsp;</span><?php echo Mage::helper('blog')->__('Read more'); ?></a>
									<div class="day-desc">
										<span class="day"><?php echo date('d', strtotime($post->getCreatedTime())) ?></span>
										<span class="month"><?php echo date('M', strtotime($post->getCreatedTime())) ?></span>
									</div>
								</div>
								<div class="latest-post-decs">
									<div class="latest-name">
										<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
									</div>
									<div class="latest-date">
										<div class="post-info text-desc">
											<span class="user-author"><?php echo $post->getUser(); ?></span>
											<?php if ($this->getCommentsEnabled()): ?>
												<?php ($post->getCommentCount() >= 1) ? $post->getCommentCount() : 0 ?> <span><a class="comments" href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo Mage::helper('blog')->__(' Comments'); ?></a></span>
											<?php endif; ?>
										</div>
										
									</div>
									<?php if($post->getShortContent()): ?>
										<p class="short-content">
											<?php if($this->getCharacterCount()!=''): ?>
												<?php echo Mage::helper('core/string')->truncate(strip_tags($post->getShortContent()), $this->getCharacterCount()); ?>
											<?php else: ?>
												<?php echo strip_tags($post->getShortContent()); ?>
											<?php endif ?>
										</p>
									<?php endif ?>
								</div>
							</div>
					<?php endforeach; ?>
				</div>
			<?php endif ?>
		<?php else: ?>
			<div class="latest-post-list">
				<?php $i=0; foreach ($posts as $post): ?>
						<div class="latest-post-info row">
							<div class="latest-post-img col-md-4 col-sm-4 col-xs-5">
								<?php if ($post->getFeaturedImage() != ''): ?>
									<a href="<?php echo $post->getAddress(); ?>" >
										<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/' . $post->getFeaturedImage(); ?>"/>
									</a>
								<?php endif ?>
							</div>
							<div class="latest-post-desc col-md-8 col-sm-8 col-xs-7">
								<?php echo $this->helper('mpanel')->getFirstImage($post->getOrigData('post_content'), $post->getAddress()) ?>
								<div class="date">
									<span class="day"><?php echo date('d', strtotime($post->getCreatedTime())) ?></span>
									<span class="month"><?php echo date('M', strtotime($post->getCreatedTime())) ?></span>
									<span class="year"><?php echo date('Y', strtotime($post->getCreatedTime())) ?></span>
								</div>
								<h4><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h4>
								<?php if($post->getShortContent()): ?>
									<p>
										<?php if($this->getCharacterCount()!=''): ?>
											<?php echo Mage::helper('core/string')->truncate(strip_tags($post->getShortContent()), $this->getCharacterCount()); ?>
										<?php else: ?>
											<?php echo strip_tags($post->getShortContent()); ?>
										<?php endif ?>
										<a href="<?php echo $post->getAddress(); ?>" class="read-more"><?php echo Mage::helper('blog')->__('read more'); ?> <i class="icon icon-angle-right"></i></a>
									</p>
								<?php endif ?>
							</div>
						</div>
				<?php endforeach; ?>
			</div>
		<?php endif ?>
	</div>
<?php else: ?>
	<div class="alert alert-danger">
		<p><?php echo $this->__('There are no posts matching the selection.') ?></p>
	</div>
<?php endif; ?>