<?php $testimonials = $this->getTestimonialsPager(); 
	$pager = $this->getCount() / $this->getPerPage();
	if($this->getCount() % $this->getPerPage() == 0) {
		$pager = $pager;
	}
	else {
		$pager = $pager + 1;
	}
?>
<div class="testimonial-list">
	<div class="row">
	<?php $count = 0; ?>
	<?php foreach($testimonials as $testimonial): ?>
		<?php $testimonial = Mage::getModel('testimonial/testimonial')->load($testimonial); ?>
		<div class="col-xs-12">
			<div class="item">
				<div class="avatar">
					<img class="img-responsive" src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'testimonial/'. $testimonial->getAvatar();  ?>" alt="<?php $testimonial->getName(); ?>" />
				</div>
				<div class="content">
					<h4 class="name"><?php echo $testimonial->getName(); ?></h4>
					<p class="information text-desc"><?php echo $testimonial->getInformation(); ?></p>
					<div class="comment"><?php echo $testimonial->getContent(); ?></div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	</div>
</div>
<div class="toolbar-bottom">
	<?php $this->getPageNumber($pager); ?>
</div>
