<?php
$categories = $this->getCategoryCollection();
$panelHelper = $this->helper('mpanel');
$size = $panelHelper->convertRatioToSize($this->getProductRatio());
if($this->getColumn()){
	$col = $this->getColumn();
	$perrow = $this->getColumn();
}
else{
	$col = 3;
	$perrow = 3;
}
$col = $panelHelper->convertColRowCustom($col);
?>
<?php //if (Mage::getStoreConfig('mpanel/catalog/featured') != ''): ?>
    <?php if (count($categories) > 0): ?>
        <div class="category-tabs">
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper">
					<div class="title-content">
						<h2><?php echo $this->getTitle() ?></h2>
					</div>
				</div>
			<?php endif ?>
			<div class="category-tabs">
				<div class="tabs-container">
					<?php if(count($categories) > 1): ?>
						<ul class="nav nav-tabs tab-menu tab-products" role="tablist">
							<?php $i = 0; foreach ($categories as $_category): $i++; ?>	
								<li <?php if ($i == 1): ?>class="active"<?php endif ?> role="presentation">
									<a href="#section-tab2-<?php echo $_category->getId(); ?>" data-number="<?php echo $i ?>" role="tab" data-toggle="tab" aria-expanded="true" >
										<span><?php echo $_category->getName() ?></span>
									</a>
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
					<div class="products tab-content">
						<?php $i = 0; foreach ($categories as $_category): $i++; ?>
							<?php $products = $this->getProductByCategory($_category) ?>
								<?php if(count($categories) > 1): ?><div class="tab-pane tab-pane<?php echo $i ?><?php if ($i == 1): ?> active<?php endif ?> section-tab2-<?php echo $i; ?>" id="section-tab2-<?php echo $_category->getId(); ?>" role="tabpanel"><?php endif ?>
									<?php if (count($products) > 0): ?>
										<div class="products-grid row">
											<?php $j=0; foreach ($products as $_product): $j++; ?>
											<?php $class = $panelHelper->getItemClass($perrow, $j) ?>
											<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
												<div class="item col-md-<?php echo $col ?> col-sm-4 col-xs-6 <?php if ($j % $perrow == 1): ?>first-row-item<?php endif; ?><?php echo $class ?>">
													<div class="product-content">
														<div class="product-top">
															<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
																<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" 
																alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
																<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
																	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
																	alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
																<?php endif  ?>																
															</a>
															<?php echo $panelHelper->getProductLabel($_product) ?>
															<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																<div class="action-quickview">
																	<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view btn-full" 
																	onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em><?php echo $this->__('Quick view'); ?></button>
																</div>
															<?php endif ?>
														</div>
														<div class="product-desc">
															<div class="top-desc">
																<div class="text-desc cate-name">
																	<div class="text">
																		<span><?php echo $_category->getName() ?></span>
																	</div>
																</div>
																<div class="controls">
																	<ul class="icon-links">
																		<?php if ($this->helper('wishlist')->isAllow() && $panelHelper->isShowWishList()) : ?>
																			<li class="wl-item"><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" <?php if (!$panelHelper->checkInWishilist($_product)) : ?>class="no-active"<?php endif ?>><em class="fa <?php if ($panelHelper->checkInWishilist($_product)) : ?>fa-heart<?php else: ?>fa-heart-o<?php endif ?>"></em></button></li>
																		<?php endif; ?>
																		<?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && $panelHelper->isShowCompare()): ?>
																			<li><button class="btn-compare" type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-sliders"></em></button></li>
																		<?php endif; ?>
																	</ul>
																</div>
															</div>
															<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></p>
															<div class="bottom-desc">
																<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
																<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short','');?>
																<?php if($panelHelper->isShowAddtoCart()): ?>
																	<?php if ($_product->isSaleable()): ?>
																		<div class="add-cart-item">
																			<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><em class="fa fa-shopping-cart"></em><?php echo $this->__('Add to Cart'); ?></button>
																		</div>
																	<?php else: ?>
																		<div class="add-cart-item">
																			<span class="text-soul"><?php echo $this->__('Out of Stock'); ?></span>
																		</div>
																	<?php endif; ?>
																<?php endif; ?>
															</div>
														</div>
													</div>
												</div>
											<?php endforeach ?>
										</div>
								<?php else: ?>
									<div class="alert alert-danger">
										<p><?php echo $this->__('There are no products matching the selection.') ?></p>
									</div>
								<?php endif ?>
							<?php if(count($categories) > 1): ?></div><?php endif ?>
						<?php endforeach ?>
					</div>
				</div>
			</div>
        </div>
	<?php else: ?>
		<div class="alert alert-danger">
			<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
		</div>
    <?php endif ?>
