<?php
/* * ****************************************************
 * Package   : Social
 * Author    : HIEPNH
 * Copyright : (c) 2014
 * ***************************************************** */
?>
<?php
$helper = Mage::helper('social');
$storeId = Mage::app()->getStore()->getStoreId();
?>
<?php if ($helper->isActived($storeId)): ?>
    <?php if (Mage::helper('social/facebook')->isActived($storeId) || Mage::helper('social/google')->isActived($storeId) || Mage::helper('social/twitter')->isActived($storeId)): ?>
        <div class="social-login-options"> 
			<a class="dropdown-toggle" data-toggle="dropdown"><span class="hidden-md hidden-sm hidden-xs"><?php echo $this->__('Social Login')?></span><span class="hidden-lg fa fa-users"></span><i class="fa fa-angle-down"></i></a>
			<div class="dropdown-menu" role="menu">
            <?php echo $this->getChildHtml('social_facebook'); ?>
            <?php echo $this->getChildHtml('social_google'); ?>
            <?php echo $this->getChildHtml('social_twitter'); ?>
			</div>
        </div>
    <?php endif; ?>
<?php endif; ?>